# Generated by Django 6.1 on 2026-08-27 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "base_manager_name": "objects",
                "ordering": ["id"],
                "verbose_name": "栏目",
                "verbose_name_plural": "栏目",
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={
                "base_manager_name": "objects",
                "ordering": ["-publish_time", "-id"],
                "verbose_name": "文章",
                "verbose_name_plural": "文章",
            },
        ),
    ]
