# Generated by Django 6.0.8 on 2026-08-27 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_alter_category_options_alter_item_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="cms.category",
                verbose_name="所属栏目",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="content",
            field=models.TextField(blank=True, verbose_name="正文"),
        ),
        migrations.AlterField(
            model_name="item",
            name="title",
            field=models.CharField(blank=True, max_length=200, verbose_name="题目"),
        ),
    ]
